=== loiane/DTD/cliente.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cliente (nome, contato)>
<!ATTLIST cliente
	id ID #REQUIRED
	situacao (ativo | inativo) "ativo"
	filial CDATA #FIXED "SÃ£o Paulo">
<!ELEMENT nome (primeiro , meio? , ultimo)>
<!ELEMENT contato (endereco+ , telefone)>
<!ELEMENT endereco (rua , numero , complemento? , bairro, cidade, estado, cep)>
<!ATTLIST endereco
	tipo (residencial | comercial) #REQUIRED
	correspondencia NMTOKEN #IMPLIED>
<!ELEMENT telefone (residencial , comercial? , celular*)>
<!ELEMENT primeiro (#PCDATA)>
<!ELEMENT meio (#PCDATA)>
<!ELEMENT ultimo (#PCDATA)>
<!ELEMENT rua (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT complemento (#PCDATA)>
<!ELEMENT bairro (#PCDATA)>
<!ELEMENT cidade (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT cep (#PCDATA)>
<!ELEMENT residencial (#PCDATA)>
<!ELEMENT comercial (#PCDATA)>
<!ELEMENT celular (#PCDATA)>

=== loiane/DTD/cliente.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cliente SYSTEM "cliente.dtd" >
<cliente id="idvalue0">
  <nome>
    <primeiro>primeiro</primeiro>
    <ultimo>ultimo</ultimo>
  </nome>
  <contato>
    <endereco tipo="residencial">
      <rua>rua</rua>
      <numero>numero</numero>
      <bairro>bairro</bairro>
      <cidade>cidade</cidade>
      <estado>estado</estado>
      <cep>cep</cep>
    </endereco>
    <telefone>
      <residencial>residencial</residencial>
    </telefone>
  </contato>
</cliente>
